name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: mkiso
        run: git clone https://github.com/debjaro/mkiso && cd mkiso && bash build.sh
