name: CI

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          sudo bash build.sh
          sudo mkdir -p /output
          sudo mv debjaro*.iso /output/debjaro-daily.iso


      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "main"
          prerelease: false
          title: "Daily build"
          files: |
            /output/*

